[build]
builder = "nixpacks"
buildCommand = "cd hxh-mysql-backend && npm install"

[deploy]
startCommand = "cd hxh-mysql-backend && node app.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.healthcheckPath]]
path = "/health"

[deploy.regions]
use = ["ap-southeast-1"]
