[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node app.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"

[deploy.regions]
use = ["ap-southeast-1"]
